### ISSUE TITLE
Pre-Publish Tasks

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter-hub#1]
Ensure the following have been completed prior to publishing the extension
```[tasklist]
### Tasks
- [x] logo.png (is this correct)
- [x] Review README.md (need a quick start)
- [x] Integration tests for web
- [x] Integration tests for desktop
- [x] Support connectihng with API tokens
- [x] Stable pipeline
- [x] Pre-Relese pipeline
- [x] Version numbers same as Jupyter extension (yes, as thats easier)
- [x] Create reles plan guide (like in Jupyter)
- [x] Create a docker container or the like for easy test
- [x] Does it work in web? Can we get it working with just an API token? (due to CORs it does not work)
- [x] Unit tests? (if we have end to end integration test, whats the point of unit tests for this)_
- [x] Contributing guide
- [x] Review gulp (optionally remove it, gulp makes CG a nighmare)
- [x] Telemetry
- [x] Tasks.json
- [x] Consume npm for Jupyter API
- [x] Localize strings
- [x] Github CI pipeline
- [x] Simpler (reduced) linter rules
- [x] Fix link to more information page for collection
- [x] Fir link to more information page for api token
- [x] Update read me to remove python extension
- [x] Update read me to mention api token
- [x] Update read me with video?
- [x] Recommend JupyterHub for JupyterHub urls from  Jupyter?
- [x] Migrate existing url from Jupyter extension?
- [x] better logging for when users report issues with auth, invalid jupyterhub url, etc
```
